
# Config file schema : https://eksctl.io/usage/schema/

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "eha-cluster"
  region: "eu-west-1"


managedNodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.micro
    amiFamily: AmazonLinux2
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: t2.micro
    amiFamily: AmazonLinux2
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    privateNetworking: true

